import { Product, Voucher, Address } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'tomsu',
    name: 'Tôm sú tươi',
    price: 329000,
    unit: '/kg',
    shop: 'Hải Sản Hà Nội - Cầu Giấy',
    voucher: 'Giảm 5% cho khách mới',
    rating: 4.8,
    distance: '1.2 km',
    isFresh: true,
    isOutOfStock: false,
    imageBg: '#FFE3D6',
    emoji: '🦐',
    ratingCount: 312,
    soldCount: 1200,
    description: 'Tôm sú tươi sống, thịt chắc ngọt, giàu dinh dưỡng. Sản phẩm được đánh bắt trong ngày và bảo quản lạnh.',
  },
  {
    id: 'muc',
    name: 'Mực một nắng',
    price: 189000,
    unit: '/gói',
    shop: 'Hải Sản Hà Nội - Cầu Giấy',
    rating: 4.7,
    distance: '1.2 km',
    isFresh: true,
    isOutOfStock: false,
    imageBg: '#E9E3D8',
    emoji: '🦑',
    description: 'Mực một nắng được phơi tự nhiên, giữ nguyên hương vị biển.',
  },
  {
    id: 'ca',
    name: 'Cá chỉ vàng',
    price: 129000,
    oldPrice: 159000,
    unit: '/gói',
    shop: 'Hải Sản Hà Nội - Long Biên',
    voucher: 'Giảm 10.000đ',
    rating: 4.6,
    distance: '3.5 km',
    isFresh: true,
    isOutOfStock: false,
    imageBg: '#FFF0C2',
    emoji: '🐟',
  },
  {
    id: 'tomkho',
    name: 'Tôm khô loại 1',
    price: 259000,
    unit: '/gói',
    shop: 'Khô Hải Sản Bảo Ngọc',
    rating: 4.9,
    distance: '2.0 km',
    isFresh: false,
    isOutOfStock: false,
    imageBg: '#FFE3D6',
    emoji: '🦐',
  },
  {
    id: 'cakho',
    name: 'Cá khô một nắng',
    price: 0,
    unit: '/gói',
    shop: 'Khô Hải Sản Bảo Ngọc',
    rating: 4.5,
    distance: '2.0 km',
    isFresh: false,
    isOutOfStock: true,
    imageBg: '#FFF0C2',
    emoji: '🐟',
  },
  {
    id: 'tomhum',
    name: 'Tôm hùm xanh',
    price: 899000,
    unit: '/kg',
    shop: 'Hải Sản Hà Nội - Cầu Giấy',
    rating: 4.9,
    distance: '1.2 km',
    isFresh: true,
    isOutOfStock: false,
    imageBg: '#DCEFEC',
    emoji: '🦞',
    ratingCount: 312,
    soldCount: 1200,
    description: 'Tôm hùm xanh tươi sống, thịt chắc ngọt, giàu dinh dưỡng. Sản phẩm được đóng gói kỹ và giao nhanh trong ngày tại Hà Nội.',
  },
];

export const MOCK_VOUCHERS: Voucher[] = [
  { code: 'MOI5', label: 'Giảm 5% cho khách hàng mới', desc: 'Đơn hàng đầu tiên · Tối đa 50.000đ', type: 'percent', value: 0.05, cap: 50000, icon: '5%' },
  { code: 'FREESHIP', label: 'Miễn phí vận chuyển', desc: 'Áp dụng cho đơn từ 200.000đ', type: 'shipping', icon: '🚚' },
  { code: 'GIAM10K', label: 'Giảm 10.000đ', desc: 'Áp dụng cho mọi đơn hàng từ 300.000đ', type: 'fixed', value: 10000, icon: '10K' },
];

export const MOCK_ADDRESS: Address = {
  name: 'Nguyễn Minh Anh',
  phone: '090 123 4567',
  full: 'Số 12, ngõ 88 Trần Duy Hưng, Cầu Giấy, Hà Nội',
};

export const TIME_SLOTS = [
  { value: '08-10', label: '08:00 - 10:00' },
  { value: '10-12', label: '10:00 - 12:00' },
  { value: '14-16', label: '14:00 - 16:00' },
  { value: '16-18', label: '16:00 - 18:00' },
  { value: '18-20', label: '18:00 - 20:00' },
];

export const CATEGORIES = [
  { id: 'fresh', name: 'Tươi sống', icon: '🦐', count: 42 },
  { id: 'sun', name: 'Một nắng', icon: '☀️', count: 18 },
  { id: 'dry', name: 'Khô hải sản', icon: '🐚', count: 26 },
  { id: 'instant', name: 'Ăn liền', icon: '🍱', count: 15 },
  { id: 'crab', name: 'Cua, ghẹ', icon: '🦀', count: 12 },
  { id: 'octopus', name: 'Bạch tuộc, mực', icon: '🐙', count: 9 },
];
